// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg_EHIGAFMUWOBKl_CMQS5pzbIGOZtkVc',
    appId: '1:674288606251:web:45e721e964416e9240de6e',
    messagingSenderId: '674288606251',
    projectId: 'otakuflow-f7f71',
    authDomain: 'otakuflow-f7f71.firebaseapp.com',
    storageBucket: 'otakuflow-f7f71.firebasestorage.app',
    measurementId: 'G-S2VNS4Y12N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEH6QqrpNtf6btEc-dJnqNVVdT5KIDp9U',
    appId: '1:674288606251:android:a6f9599e4ff527f940de6e',
    messagingSenderId: '674288606251',
    projectId: 'otakuflow-f7f71',
    storageBucket: 'otakuflow-f7f71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuUjdbsCS0tcNnsw3HFU4alpkY-Ct6LwU',
    appId: '1:674288606251:ios:8d8a52e1224a087540de6e',
    messagingSenderId: '674288606251',
    projectId: 'otakuflow-f7f71',
    storageBucket: 'otakuflow-f7f71.firebasestorage.app',
    iosBundleId: 'com.sptrl.otakuflow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuUjdbsCS0tcNnsw3HFU4alpkY-Ct6LwU',
    appId: '1:674288606251:ios:f67fc01d6419580440de6e',
    messagingSenderId: '674288606251',
    projectId: 'otakuflow-f7f71',
    storageBucket: 'otakuflow-f7f71.firebasestorage.app',
    iosBundleId: 'com.trl.startupLaunch',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDg_EHIGAFMUWOBKl_CMQS5pzbIGOZtkVc',
    appId: '1:674288606251:web:2fce50ed5a4328aa40de6e',
    messagingSenderId: '674288606251',
    projectId: 'otakuflow-f7f71',
    authDomain: 'otakuflow-f7f71.firebaseapp.com',
    storageBucket: 'otakuflow-f7f71.firebasestorage.app',
    measurementId: 'G-52Q9RXYEZR',
  );
}
